clf;
hold on;
set(gca,'xtick',-4:2.0:4);
set(gca,'ytick',-2:2.0:2);
xlim ([-5 5]);
ylim ([-3 3]);
ax = gca;
ax.XAxisLocation = 'origin';
ax.YAxisLocation = 'origin';
x = -4:0.01:4;
y = x./(x.^2+1);
plot(x,y, 'r', 'LineWidth', 2);
y = x./(x.^2+1);
plot(x,y, 'r', 'LineWidth', 2);
txt = 'x';
text(8.2,-0.5,txt, 'FontSize', 14);
txt = 'y';
text(0.7,2.7,txt, 'FontSize', 14);
txt = 'sin(x)/x';
text(6.5, 0.5,txt, 'FontSize', 14);
% AH --> y = 0
x = -5:0.01:-3;
y = x*0;
plot(x,y, 'b--', 'LineWidth', 2);
x = 3:0.01:5;
y = x*0;
plot(x,y, 'b--', 'LineWidth', 2);
txt = 'y = 0';
text(4.2,0.4,txt);
txt= '\downarrow';
text(4.5,0.2,txt);
hold off;