clf;
hold on;
set(gca,'xtick',-8:2.0:8);
set(gca,'ytick',-2:2.0:2);
xlim ([-9 9]);
ylim ([-3 3]);
ax = gca;
ax.XAxisLocation = 'origin';
ax.YAxisLocation = 'origin';
x = -8:0.01:8;
y = sin(x)./x;
plot(x,y, 'r', 'LineWidth', 2);
plot(0,1, 'ok');
y = sin(x)./x;
plot(x,y, 'r', 'LineWidth', 2);
txt = 'x';
text(8.2,-0.5,txt, 'FontSize', 14);
txt = 'y';
text(0.7,2.7,txt, 'FontSize', 14);
txt = 'sin(x)/x';
text(6.5, 0.5,txt, 'FontSize', 14);
x = -10:0.01:10;
y = x*0;
plot(x,y, 'b--', 'LineWidth', 2);
txt = 'y = 0';
text(4.2,0.4,txt);
txt= '\downarrow';
text(4.5,0.2,txt);
hold off;