clf;
hold on;
set(gca,'xtick',-4:2.0:4);
set(gca,'ytick',-6:2.0:4);
xlim ([-5 5]);
ylim ([-7 6]);
ax = gca;
ax.XAxisLocation = 'origin';
ax.YAxisLocation = 'origin';
x = -4:0.01:4;
y = x.*exp(-1./x);
plot(x,y, 'b', 'LineWidth', 2);
plot(0,0, 'ok');
x = -4:0.01:4.5;
y = x.*exp(-1./x);
plot(x,y, 'r', 'LineWidth', 2);
txt = 'x';
text(4.5,0.4,txt, 'FontSize', 14);
txt = 'y';
text(-0.4,5,txt, 'FontSize', 14);
txt = 'x*exp(-1/x)';
text(0.2, 4.7,txt, 'FontSize', 14);
y = x-1;
plot(x,y, 'k--', 'LineWidth', 1);
txt = ' y = x - 1 \rightarrow';
text(-3,-2.5,txt);
hold off;