function graphsLineSearch(Lista,LNit,Lopt) 

%%%%%%%%% Graphical treatement of Line search for  Nvar=2 variables
%%%%%%%%% functions
%%%%%%%%% 
%%%%%%%%% Inputs: objsctive function; Lista=list of x_k's.  
%%%%%%%%%%%%%%%%% LNit=list of numb of iterations (more than 1 seed)
%%%%%%%%%%%%%%%%% 
%%%%%%%%% output: graph of generated (by line search) sequences over level
%%%%%%%%% sets
%%%%%%%%%%%%%%%%%



Ninicial=1;    %% 1st Ninicial

for i=1:length(LNit)  %% length(LNit) equal number of seeds
    Nfinal=Ninicial+LNit(i)-1;
        Lx=Lista(1,Ninicial:Nfinal); % x values of sequence for seed number i 
        Ly=Lista(2,Ninicial:Nfinal); % y values of sequence for seed number i  
        hold on
        plot(Lx,Ly,'ro-') %% draws sequence generated by seed i
        plot(Lista(1,Ninicial),Lista(2,Ninicial),'go',...
            'LineWidth',4,'MarkerSize',20) %% seed i green ball
        plot(Lista(1,Nfinal),Lista(2,Nfinal),'x',...
            'LineWidth',4, 'MarkerSize',20) %% optimum i blue cross    
    Ninicial=Nfinal+1;    %% new Ninicial
end

hold off