function graficosLineSearchNvar1(f,Lista,LNit,Lopt) 

%%%%%%%%% Graphical treatement of Line search for  Nvar=1 variable
%%%%%%%%% functions
%%%%%%%%% 
%%%%%%%%% Inputs: objsctive function; Lista=list of x_k's.  
%%%%%%%%%%%%%%%%% LNit=list of numb of iterations (more than 1 seed)
%%%%%%%%%%%%%%%%% 
%%%%%%%%% output: graph of generated (by line search) sequences over graph
%%%%%%%%% of objective function
%%%%%%%%%
%%%%%%%%%%%%%%%%%


Ninicial=1;    %% 1st Ninicial

for i=1:length(LNit)  %% length(LNit) equal number of seeds
    Nfinal=Ninicial+LNit(i)-1;
        Lx=Lista(1,Ninicial:Nfinal); % x values of sequence for seed number i 
        Ly=[];
        for j=1:length(Lx)
        Ly=[Ly f(Lx(j))]; % y values of sequence for seed number i 
        hold on
        end
        plot(Lx,Ly,'ro-') %% draws sequence generated by seed i
        plot(Lista(Ninicial),f(Lista(Ninicial)),'go',...
            'LineWidth',4,'MarkerSize',20)  %% seed i green ball
        plot(Lista(Nfinal),f(Lista(Nfinal)),'x',...
            'LineWidth',4, 'MarkerSize',20) %% optimum i blue cross  
    Ninicial=Nfinal+1;    %% new Ninicial
end

hold off